### ISSUE TITLE
"Cannot set headers after they are sent to the client" when visiting home logged in

### ISSUE THREAD

**Issue by cirosantilli** [Varun-Hegde/Conduit_NodeJS#2]
Fix: https://github.com/cirosantilli/Conduit_NodeJS/commit/0099adfba42729cb7632f2b7e081c2b3269ef213#diff-30caa90706d3a2cdb7be281b1f0ca6d5b613c60326e5f2ebb5544edbfb904c0eR277

Because two res.json were called when there are no followers.

```    
    (node:196962) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
        at ServerResponse.setHeader (_http_outgoing.js:558:11)
        at ServerResponse.header (/home/ciro/git/Conduit_NodeJS/node_modules/express/lib/response.js:771:10)
        at ServerResponse.json (/home/ciro/git/Conduit_NodeJS/node_modules/express/lib/response.js:264:10)
        at module.exports.getFeed (/home/ciro/git/Conduit_NodeJS/controllers/articles.js:299:33)
```

**Comment by Varun-Hegde** [comment]
Fixed the issue and also updated the error messages. 👍
